FROM ubuntu:latest
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y python3 python3-pip
RUN rm /usr/lib/python3/dist-packages/EXTERNALLY-MANAGED 2>/dev/null || rm /usr/lib/python3*/EXTERNALLY-MANAGED 2>/dev/null || true
RUN pip3 install flask
WORKDIR /app
COPY ./api.py /app/api.py
CMD ["python3", "api.py"]
